# Generated by Django 4.2.1 on 2023-07-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default='stock', max_length=50, verbose_name='Cantidad'),
        ),
    ]
